### PR TITLE
Compiling a two phase commit protocol

### PR DESCRIPTION
**Pull request by rmascarenhas**
I added a `2pc.tla` spec, based on the spec available at: http://lamport.azurewebsites.net/tla/two-phase.html. I made changes to Lamport's original specs, and they are listed in the comments in the top of that file.

Things that are unclear and need to be explored further:

* Compilation of `either`. Instead of pseudo-randomly choosing a branch of `either` statements, we can generate a function where the developer implements the actual application logic that decides which concrete path should be taken.

Example/draft:

Given the following spec:

~~~tla
either { doA() } or { doB() } or { doC() }
~~~

PGo could translate that to:

~~~go
// locals: all variables that are local to the PlusCal process
func Decide(locals) string {
  // app logic
  // returns one of: "doA" or "doB" or "doC"
  
  // by default, it could return a random choice, but hopefully the developer
  // will add code that makes sense in the application where two-phase commit
  // is being used
  return []string{"doA", "doB", "doC"}[rand.Intn(3)]
}

switch decision := Decide(locals) {
case "doA":
  doA(); // expansion of doA macro
case "doB":
  doB(); // expansion of doB macro
case "doC":
  doC(); // expansion of doC macro
default:
  panic("Unknown 'either' branch: %s", decision)
}
~~~

* Network: the original spec uses a set of records. Perhaps a better representation would use sequences

* Type checking does not work for functions defined as `[rm \in RM |-> "working"]`. `\in` is still unsupported.

* Unclear how the code generated by PGo would be integrated in a larger application that wishes to use a two-phase commit protocol for its operation without making significant code changes.

### CODE REVIEW

**Comment by bestchai** [comment]
I would like to see an example of the use of either that would actually be useful if compiled in this way. I consider either as a MC exploration hint/heuristic. It would be helpful to see a bunch of examples (like a dozen or more) drawn from real specs and then figure out what the right compilation strategy is in each one.

**Comment by mrordinaire** [comment]
- [Shared two-sided queue using a double compare-and-swap (DCAS)](https://lamport.azurewebsites.net/tla/dcas-example.html) uses `either` no non-deterministically insert and delete elements of a shared queue.
- [Alternating bit protocol](https://github.com/UBC-NSS/pgo/blob/939ecad7750a17b74453d1f4a7a5f654156d4610/test/pluscal/AltBitProtocol.tla) uses `either` to (1) non-deterministically buffer more messages into the input queue, (2) send a message on the network (when there is more input to be sent), (3) receive a message from the network (when there is a message to be received), and (4) remove messages from in-flight messages in the network.
- [@wantonsolution's two phase commit](https://github.com/UBC-NSS/pgo/blob/939ecad7750a17b74453d1f4a7a5f654156d4610/examples/pgo2pc.tla) and [this two phase commit](https://github.com/UBC-NSS/pgo/blob/7e21c42336c98b2ee43207f3a6963791b8ca3a7e/examples/2pc.tla) use `either` to model network communication, machine failures, and timeouts.
- Specifications found at http://lamport.azurewebsites.net/tla/byzpaxos.html also use `either` but I don't know what the intent is.

**Comment by fhackett** [comment]
To jump on the `either` train, my original idea for implementing either was to write code that attempts each branch sequentially (and loops back to the first if it fails all of them).

One particular advantage of this approach would be that it would correctly compile all of the examples @mrordinaire posted, since the behaviour that seems to be intended is "do whichever one works first". Even when `either` is used without await to implement non-determinism this model will be trivially correct by always choosing the first branch, which should always be a valid option.

Clearly this approach would make attempts at using `either` to model non-determinism useless, but I think we need a better way to do that anyway. See #75 for a refinement of the idea I send to pgo-dev a while back. That addresses both this and a lot of other issues I ran into trying to make the module system work.

**Comment by rmascarenhas** [comment]
Closing this since due to the ongoing work based on #75. The 2pc spec here may still be useful in the future (it currently uses a number of unsupported TLA+ features), but we can always come back to it.

**Pull request closed without merging**
