### PR TITLE
Fix CI upload artifact

### PR DESCRIPTION
**Pull request by shayanh**
Fixed path in ci upload artifact and temporary changes for testing it

### CODE REVIEW

**Comment by shayanh** [comment]
I suggest "squash and merge" to exclude the first commit.

**Comment by fhackett** [comment]
Squash and merge is fine.

Just to check, though, I'm confused what this is fixing. It's always worked for my PRs... ?
If there was originally an issue, it would be nice to document what it was.

**Comment by shayanh** [comment]
That's strange. Could you send me a link that artifact uploading works fine?

**Comment by shayanh** [comment]
For example, in the this run the artifacts didn't upload because of wrong path:
https://github.com/UBC-NSS/pgo/runs/3207289282

**Comment by fhackett** [comment]
Ah, right. That is an issue, but maybe not what you think it is. Here's an example of it working correctly: https://github.com/UBC-NSS/pgo/runs/3206851906

The path isn't wrong, the files just aren't there. So, the action is actually working as designed. Then problem is that the error occurs too early for the outputs to be written out, at this line https://github.com/UBC-NSS/pgo/blob/master/test/pgo/TLAExpressionFuzzTests.scala#L70

Usually an error on that line is a bug in the fuzz tester itself... but I imagine this PR could be altered to add output for this case, as it's probably easier to have it than not.

**Comment by bestchai** [comment]
+1 for adding output in this case

**Comment by shayanh** [comment]
Fixed in #152.

**Pull request closed without merging**
