### PR TITLE
Either implementation with sequential tries

### LINKED ISSUE #11: Support PlusCal either statement
The `either` statement executes a random non-blocking clause. We could implement this with `select` in Go, but it's difficult to get it into a format where `select` works.

Original issue: https://bitbucket.org/whiteoutblackout/pgo/issues/39/support-pluscal-either-statement

### PR DESCRIPTION
**Pull request by mrordinaire**
This PR implements `either` by sequentially trying each case of the `either` statement.

Fixes #11.

### CODE REVIEW

**Comment by bestchai** [comment]
- Add a test for executing the other branch of either.
- Add a test that executed the either clause multiple times, waiting for await to succeed (and eventually it does)

**Comment by mrordinaire** [comment]
I've added a test for running both cases of the either statement (see [EitherBothBranches.tla](https://github.com/UBC-NSS/pgo/pull/78/files#diff-bc807b7ebeeb022440003289d628ae98)), as well as running an either statement repeatedly (see [EitherRepeatedExec.tla](https://github.com/UBC-NSS/pgo/pull/78/files#diff-ba63235be8c02e2545b3728e63b4cdc5)).

**Comment by fhackett** [comment]
@mrordinaire I just did a quick merge from master as I just merged @adam-tg 's PR for CASE expressions and the EitherRepeatedExec test seems to get stuck - any ideas?

**Comment by fhackett** [comment]
that's interesting... it works on Travis, but not on my machine.

**Comment by mrordinaire** [comment]
Unfortunately, `@Ignore` does not work for parameterized tests. I've commented the test out.

**Comment by rmascarenhas** [comment]
I would have preferred if we tried to change the spec so that the behavior of the compiled source did not rely on fairness guarantees instead of commenting out the test. Is that possible?

**Comment by mrordinaire** [comment]
@rmascarenhas, I've simplified the test and added it back into the test suite (see f4b700f9cff057702ecacf772c50a306da2817e8).

**Pull request merged**
